export const UPDATE_PRODUCTID = "UPDATE_PRODUCTID";
export const UPDATE_ATTRIBUTEVALUE = "UPDATE_ATTRIBUTEVALUE";
export const UPDATE_MANUFACTURE = "UPDATE_MANUFACTURE";
export const UPDATE_PRICE = "UPDATE_PRICE";
export const UPDATE_DISCOUNT = "UPDATE_DISCOUNT";
export const UPDATE_CLASSIFICATION = "UPDATE_CLASSIFICATION";
export const UPDATE_CLASSIFICATIONGROUP = "UPDATE_CLASSIFICATIONGROUP";
export const UPDATE_CATALOGID = "UPDATE_CATALOGID";
export const UPDATE_SHORTDESCRIPTION = "UPDATE_SHORTDESCRIPTION";
export const UPDATE_LONGDESCRIPTION = "UPDATE_LONGDESCRIPTION";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";

